{
    imagen_para_mostrar,
    tipo_de_Identificación,
    numero_de_Identificación,
    primer_Nombre,
    segundo_Nombre,
    primer_Apellido,
    segundo_Apellido,
    dirección_FK,
    email,
    telefono,
    sexo,
    fecha_de_Nacimiento,
    fecha_de_Registro
}